---
title: "Evaluaciones"
---

El curso contempla las siguientes evaluaciones:

-   4 tareas (40%)
-   Un proyecto (60%)

[Si cumple alguna de las siguientes condiciones, deberá además rendir una <strong>prueba final:</strong>]{.my-red}

-   Su promedio de tareas es igual o inferior a 55.
-   Su nota de proyecto es igual o inferior a 55.
-   Su porcentaje de asistencia es inferior al 70%.
-   Poseer alguna sanción relacionada con las [políticas del curso](course-syllabus.html).

En ese caso las ponderaciones para el cálculo del promedio final serán: Tareas (20%), proyecto (40%), prueba final (40%).

## Tareas

Las tareas serán publicadas en el [enlace](index.html).

La entrega de las tareas debe realizarse hasta las 23:59 horas de la fecha indicada. Recuerde que, si por algún motivo se retrasa en la entrega en la fecha y hora indicada, puede hacer uso de sus ["días de retraso"](course-syllabus.html#entregas-tardias).

Las tareas deben entregarse vía [Aula Virtual](https://aula.usm.cl/) siguiendo estrictamente las instrucciones dadas en cada una de las tareas.

## Proyectos

Los proyectos deben desarrollarse durante el transcurso del semestre (no al final). Los hitos relacionados a los proyectos están disponibles en el [enlace](index.html).

Para las presentaciones finales no puede hacer uso de sus ["días de retraso"](course-syllabus.html) disponibles.

Al final del semestre deberá hacer una presentación de 15 min, entregar un informe escrito y poner a disposición del curso un video explicativo del proyecto, el informe escrito y la implementación realizada.

Los temas son a elección de los estudiantes. Algunos temas posibles son:

-   Análisis causal usando Machine Learning, contrastive learning, ...
-   Manifold learning.
-   NLP / knowledge graph usando [OMIM](https://www.omim.org/).
-   Análisis de redes cerebrales en ASD (Autism Spectrum Disorders) - fMRI.
-   Implementación de una red difusa profunda.